#pragma once

//IO communication codes

#define IO_REQUEST_PIDS CTL_CODE(FILE_DEVICE_UNKNOWN, 0x85100000, METHOD_BUFFERED, FILE_SPECIAL_ACCESS)
#define IO_REQUEST_INITIALIZED CTL_CODE(FILE_DEVICE_UNKNOWN, 0x85200000, METHOD_BUFFERED, FILE_SPECIAL_ACCESS)
#define IO_REQUEST_HEARTBEAT CTL_CODE(FILE_DEVICE_UNKNOWN, 0x85300000, METHOD_BUFFERED, FILE_SPECIAL_ACCESS)
#define IO_REQUEST_UNLOAD CTL_CODE(FILE_DEVICE_UNKNOWN, 0x85400000, METHOD_BUFFERED, FILE_SPECIAL_ACCESS)


typedef struct _PROCDATA
{
	ULONG Launcher;
	ULONG Steam;
	ULONG CSRSS;
	ULONG CSRSS2;
	ULONG Services;

} PROCDATA, * PPROCDATA;

typedef struct _HEARTBEAT
{
	BOOLEAN PsCallbacks;
	BOOLEAN ObCallbacks;

	//For IOCTL Validation
	ULONG SenderPID;

} HEARTBEAT, * PHEARTBEAT;

//IO Prototypes
NTSTATUS IoControl(PDEVICE_OBJECT pDeviceObject, PIRP pIRP);
NTSTATUS IoCloseCall(PDEVICE_OBJECT pDeviceObject, PIRP pIRP);
NTSTATUS IoCreateCall(PDEVICE_OBJECT pDeviceObject, PIRP pIRP);